from .animal_requests import get_all_animals, get_single_animal, get_animals_by_location, get_animals_by_status, delete_animal, update_animal, create_animal
from .customer_requests import get_all_customers, get_single_customer, get_customers_by_email
from .location_requests import get_all_locations, get_single_location
from .employee_requests import get_all_employees, get_single_employee, get_employees_by_location, create_employee